exchange:
  bitflyer:
    api_key: ""
    api_secret: ""
    symbols:
      - BTC_JPY
      - XRP_JPY
      - ETH_JPY
      - XLM_JPY
      - MONA_JPY
      - ELF_JPY
      # - ETH_BTC
      # - BCH_BTC 
      - FX_BTC_JPY
    dry_run: []
    invest_money: 10000
    loss_cut: 40000

connection_string: "mariadb+mariadbconnector://tradebot:{your_password}@127.0.0.1:3306/tradedb"