exchange:
  bitflyer:
    api_key: ""
    api_secret: ""
    symbols:
      - BTC_JPY
      - XRP_JPY
    dry_run: []

connection_string: "mariadb+mariadbconnector://tradebot:{your_password}@127.0.0.1:3306/tradedb"